# Generated by Django 3.0.5 on 2020-10-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=4)),
                ('image', models.CharField(max_length=2000)),
                ('company', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('quantity', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=30, verbose_name='car type')),
                ('description', models.TextField()),
                ('is_store', models.BooleanField(default=True, verbose_name='is store')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
